!  This file was generated by kmcos (kinetic Monte Carlo of Systems)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2013.
!  The model was written by Lucas Yuan.

!  This file is part of kmcos.
!
!  kmcos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmcos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmcos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA
!****h* kmcos/lattice
! FUNCTION
!    Implements the mappings between the real space lattice
!    and the 1-D lattice, which kmcos/base operates on.
!    Furthermore replicates all geometry specific functions of kmcos/base
!    in terms of lattice coordinates.
!    Using this module each site can be addressed with 4-tuple
!    ``(i, j, k, n)`` where ``i, j, k`` define the unit cell and
!    ``n`` the site within the unit cell.
!
!******


module lattice
use kind_values
use base, only: &
    assertion_fail, &
    base_deallocate_system => deallocate_system, &
    get_kmc_step, &
    get_kmc_time, &
    get_kmc_time_step, &
    get_rate, &
    increment_procstat, &
    base_add_proc => add_proc, &
    base_reset_site => reset_site, &
    base_allocate_system => allocate_system, &
    base_can_do => can_do, &
    base_del_proc => del_proc, &
    determine_procsite, &
    base_replace_species => replace_species, &
    base_get_species => get_species, &
    base_get_volume => get_volume, &
    reload_system => reload_system, &
    save_system, &
    assertion_fail, &
    set_rate_const, &
    update_accum_rate, &
    update_clocks



implicit none

integer(kind=iint), dimension(3), public :: system_size
integer(kind=iint), parameter, public :: nr_of_layers = 1

 ! Layer constants

integer(kind=iint), parameter, public :: model_dimension = 1
integer(kind=iint), parameter, public :: tpb_line = 0
integer(kind=iint), public :: default_layer = tpb_line
integer(kind=iint), public :: substrate_layer = tpb_line

 ! Site constants

real(kind=rsingle), dimension(3,3), public :: unit_cell_size = 0.
real(kind=rsingle), dimension(110, 3), public :: site_positions
integer(kind=iint), parameter, public :: tpb_line_0_0_substrate = 1
integer(kind=iint), parameter, public :: tpb_line_0_1_boundary = 2
integer(kind=iint), parameter, public :: tpb_line_0_2_boundary = 3
integer(kind=iint), parameter, public :: tpb_line_0_3_boundary = 4
integer(kind=iint), parameter, public :: tpb_line_0_4_boundary = 5
integer(kind=iint), parameter, public :: tpb_line_0_5_boundary = 6
integer(kind=iint), parameter, public :: tpb_line_0_6_boundary = 7
integer(kind=iint), parameter, public :: tpb_line_0_7_boundary = 8
integer(kind=iint), parameter, public :: tpb_line_0_8_boundary = 9
integer(kind=iint), parameter, public :: tpb_line_0_9_boundary = 10
integer(kind=iint), parameter, public :: tpb_line_0_10_boundary = 11
integer(kind=iint), parameter, public :: tpb_line_1_0_substrate = 12
integer(kind=iint), parameter, public :: tpb_line_1_1_active = 13
integer(kind=iint), parameter, public :: tpb_line_1_2_bulk = 14
integer(kind=iint), parameter, public :: tpb_line_1_3_bulk = 15
integer(kind=iint), parameter, public :: tpb_line_1_4_bulk = 16
integer(kind=iint), parameter, public :: tpb_line_1_5_bulk = 17
integer(kind=iint), parameter, public :: tpb_line_1_6_bulk = 18
integer(kind=iint), parameter, public :: tpb_line_1_7_bulk = 19
integer(kind=iint), parameter, public :: tpb_line_1_8_bulk = 20
integer(kind=iint), parameter, public :: tpb_line_1_9_bulk = 21
integer(kind=iint), parameter, public :: tpb_line_1_10_bulk = 22
integer(kind=iint), parameter, public :: tpb_line_2_0_substrate = 23
integer(kind=iint), parameter, public :: tpb_line_2_1_active = 24
integer(kind=iint), parameter, public :: tpb_line_2_2_bulk = 25
integer(kind=iint), parameter, public :: tpb_line_2_3_bulk = 26
integer(kind=iint), parameter, public :: tpb_line_2_4_bulk = 27
integer(kind=iint), parameter, public :: tpb_line_2_5_bulk = 28
integer(kind=iint), parameter, public :: tpb_line_2_6_bulk = 29
integer(kind=iint), parameter, public :: tpb_line_2_7_bulk = 30
integer(kind=iint), parameter, public :: tpb_line_2_8_bulk = 31
integer(kind=iint), parameter, public :: tpb_line_2_9_bulk = 32
integer(kind=iint), parameter, public :: tpb_line_2_10_bulk = 33
integer(kind=iint), parameter, public :: tpb_line_3_0_substrate = 34
integer(kind=iint), parameter, public :: tpb_line_3_1_active = 35
integer(kind=iint), parameter, public :: tpb_line_3_2_bulk = 36
integer(kind=iint), parameter, public :: tpb_line_3_3_bulk = 37
integer(kind=iint), parameter, public :: tpb_line_3_4_bulk = 38
integer(kind=iint), parameter, public :: tpb_line_3_5_bulk = 39
integer(kind=iint), parameter, public :: tpb_line_3_6_bulk = 40
integer(kind=iint), parameter, public :: tpb_line_3_7_bulk = 41
integer(kind=iint), parameter, public :: tpb_line_3_8_bulk = 42
integer(kind=iint), parameter, public :: tpb_line_3_9_bulk = 43
integer(kind=iint), parameter, public :: tpb_line_3_10_bulk = 44
integer(kind=iint), parameter, public :: tpb_line_4_0_substrate = 45
integer(kind=iint), parameter, public :: tpb_line_4_1_active = 46
integer(kind=iint), parameter, public :: tpb_line_4_2_bulk = 47
integer(kind=iint), parameter, public :: tpb_line_4_3_bulk = 48
integer(kind=iint), parameter, public :: tpb_line_4_4_bulk = 49
integer(kind=iint), parameter, public :: tpb_line_4_5_bulk = 50
integer(kind=iint), parameter, public :: tpb_line_4_6_bulk = 51
integer(kind=iint), parameter, public :: tpb_line_4_7_bulk = 52
integer(kind=iint), parameter, public :: tpb_line_4_8_bulk = 53
integer(kind=iint), parameter, public :: tpb_line_4_9_bulk = 54
integer(kind=iint), parameter, public :: tpb_line_4_10_bulk = 55
integer(kind=iint), parameter, public :: tpb_line_5_0_substrate = 56
integer(kind=iint), parameter, public :: tpb_line_5_1_active = 57
integer(kind=iint), parameter, public :: tpb_line_5_2_bulk = 58
integer(kind=iint), parameter, public :: tpb_line_5_3_bulk = 59
integer(kind=iint), parameter, public :: tpb_line_5_4_bulk = 60
integer(kind=iint), parameter, public :: tpb_line_5_5_bulk = 61
integer(kind=iint), parameter, public :: tpb_line_5_6_bulk = 62
integer(kind=iint), parameter, public :: tpb_line_5_7_bulk = 63
integer(kind=iint), parameter, public :: tpb_line_5_8_bulk = 64
integer(kind=iint), parameter, public :: tpb_line_5_9_bulk = 65
integer(kind=iint), parameter, public :: tpb_line_5_10_bulk = 66
integer(kind=iint), parameter, public :: tpb_line_6_0_substrate = 67
integer(kind=iint), parameter, public :: tpb_line_6_1_active = 68
integer(kind=iint), parameter, public :: tpb_line_6_2_bulk = 69
integer(kind=iint), parameter, public :: tpb_line_6_3_bulk = 70
integer(kind=iint), parameter, public :: tpb_line_6_4_bulk = 71
integer(kind=iint), parameter, public :: tpb_line_6_5_bulk = 72
integer(kind=iint), parameter, public :: tpb_line_6_6_bulk = 73
integer(kind=iint), parameter, public :: tpb_line_6_7_bulk = 74
integer(kind=iint), parameter, public :: tpb_line_6_8_bulk = 75
integer(kind=iint), parameter, public :: tpb_line_6_9_bulk = 76
integer(kind=iint), parameter, public :: tpb_line_6_10_bulk = 77
integer(kind=iint), parameter, public :: tpb_line_7_0_substrate = 78
integer(kind=iint), parameter, public :: tpb_line_7_1_active = 79
integer(kind=iint), parameter, public :: tpb_line_7_2_bulk = 80
integer(kind=iint), parameter, public :: tpb_line_7_3_bulk = 81
integer(kind=iint), parameter, public :: tpb_line_7_4_bulk = 82
integer(kind=iint), parameter, public :: tpb_line_7_5_bulk = 83
integer(kind=iint), parameter, public :: tpb_line_7_6_bulk = 84
integer(kind=iint), parameter, public :: tpb_line_7_7_bulk = 85
integer(kind=iint), parameter, public :: tpb_line_7_8_bulk = 86
integer(kind=iint), parameter, public :: tpb_line_7_9_bulk = 87
integer(kind=iint), parameter, public :: tpb_line_7_10_bulk = 88
integer(kind=iint), parameter, public :: tpb_line_8_0_substrate = 89
integer(kind=iint), parameter, public :: tpb_line_8_1_active = 90
integer(kind=iint), parameter, public :: tpb_line_8_2_bulk = 91
integer(kind=iint), parameter, public :: tpb_line_8_3_bulk = 92
integer(kind=iint), parameter, public :: tpb_line_8_4_bulk = 93
integer(kind=iint), parameter, public :: tpb_line_8_5_bulk = 94
integer(kind=iint), parameter, public :: tpb_line_8_6_bulk = 95
integer(kind=iint), parameter, public :: tpb_line_8_7_bulk = 96
integer(kind=iint), parameter, public :: tpb_line_8_8_bulk = 97
integer(kind=iint), parameter, public :: tpb_line_8_9_bulk = 98
integer(kind=iint), parameter, public :: tpb_line_8_10_bulk = 99
integer(kind=iint), parameter, public :: tpb_line_9_0_substrate = 100
integer(kind=iint), parameter, public :: tpb_line_9_1_active = 101
integer(kind=iint), parameter, public :: tpb_line_9_2_bulk = 102
integer(kind=iint), parameter, public :: tpb_line_9_3_bulk = 103
integer(kind=iint), parameter, public :: tpb_line_9_4_bulk = 104
integer(kind=iint), parameter, public :: tpb_line_9_5_bulk = 105
integer(kind=iint), parameter, public :: tpb_line_9_6_bulk = 106
integer(kind=iint), parameter, public :: tpb_line_9_7_bulk = 107
integer(kind=iint), parameter, public :: tpb_line_9_8_bulk = 108
integer(kind=iint), parameter, public :: tpb_line_9_9_bulk = 109
integer(kind=iint), parameter, public :: tpb_line_9_10_bulk = 110

 ! spuck = Sites Per Unit Cell Konstant
integer(kind=iint), parameter, public :: spuck = 110
 ! lookup tables
integer(kind=iint), dimension(:, :), allocatable, public :: nr2lattice
integer(kind=iint), dimension(:,:,:,:), allocatable, public :: lattice2nr



contains

pure function calculate_lattice2nr(site)

!****f* lattice/calculate_lattice2nr
! FUNCTION
!    Maps all lattice coordinates onto a continuous
!    set of integer :math:`\in [1,volume]`
!
! ARGUMENTS
!
!    - ``site`` integer array of size (4) a lattice coordinate
!******
    integer(kind=iint), dimension(4), intent(in) :: site
    integer(kind=iint) :: calculate_lattice2nr

    ! site = (x,y,z,local_index)
    calculate_lattice2nr = spuck*(modulo(site(1), system_size(1)))+site(4)

end function calculate_lattice2nr

pure function calculate_nr2lattice(nr)

!****f* lattice/calculate_nr2lattice
! FUNCTION
!    Maps a continuous set of
!    of integers :math:`\in [1,volume]` to a
!    4-tuple representing a lattice coordinate
!
! ARGUMENTS
!
!    - ``nr`` integer representing the site index
!******
    integer(kind=iint), intent(in) :: nr
    integer(kind=iint), dimension(4) :: calculate_nr2lattice

    calculate_nr2lattice(3) = 0
    calculate_nr2lattice(2) = 0
    calculate_nr2lattice(1) = (nr - 1) / spuck
    calculate_nr2lattice(4) = nr - spuck*calculate_nr2lattice(1)

end function calculate_nr2lattice

subroutine allocate_system(nr_of_proc, input_system_size, system_name, buffer_parameter, threshold_parameter, execution_steps, save_limit)

!****f* lattice/allocate_system
! FUNCTION
!    Allocates system, fills mapping cache, and
!    checks whether mapping is consistent
!
! ARGUMENTS
!
!    ``none``
!******
    integer(kind=iint), intent(in) :: nr_of_proc, execution_steps, save_limit
    real(kind=rdouble), intent(in) :: threshold_parameter, buffer_parameter
    integer(kind=iint), dimension(1), intent(in) :: input_system_size
    character(len=200), intent(in) :: system_name

    integer(kind=iint) :: i, j, k, nr
    integer(kind=iint) :: check_nr
    integer(kind=iint) :: volume

    ! Copy to module wide variable
    system_size = (/input_system_size(1), 1, 1/)
    volume = system_size(1)*system_size(2)*system_size(3)*spuck
    ! Let's check if the works correctly, first
    ! and if so populate lookup tables
    do k = 0, system_size(3)-1
        do j = 0, system_size(2)-1
            do i = 0, system_size(1)-1
                do nr = 1, spuck
                    if(.not.all((/i,j,k,nr/).eq. &
                    calculate_nr2lattice(calculate_lattice2nr((/i,j,k,nr/)))))then
                        print *,"Error in Mapping:"
                        print *, (/i,j,k,nr/), "was mapped on", calculate_lattice2nr((/i,j,k,nr/))
                        print *, "but that was mapped on", calculate_nr2lattice(calculate_lattice2nr((/i,j,k,nr/)))
                        stop
                    endif
                end do
            end do
        end do
    end do

    do check_nr=1, product(system_size)*spuck
        if(.not.check_nr.eq.calculate_lattice2nr(calculate_nr2lattice(check_nr)))then
            print *, "ERROR in Mapping:", check_nr
            print *, "was mapped on", calculate_nr2lattice(check_nr)
            print *, "but that was mapped on",calculate_lattice2nr(calculate_nr2lattice(check_nr))
            stop
        endif
    end do

    allocate(nr2lattice(1:product(system_size)*spuck,4))
    allocate(lattice2nr(-system_size(1):2*system_size(1)-1, &
        -system_size(2):2*system_size(2)-1, &
        -system_size(3):2*system_size(3)-1, &
         1:spuck))
    do check_nr=1, product(system_size)*spuck
        nr2lattice(check_nr, :) = calculate_nr2lattice(check_nr)
    end do
    do k = -system_size(3), 2*system_size(3)-1
        do j = -system_size(2), 2*system_size(2)-1
            do i = -system_size(1), 2*system_size(1)-1
                do nr = 1, spuck
                    lattice2nr(i, j, k, nr) = calculate_lattice2nr((/i, j, k, nr/))
                end do
            end do
        end do
    end do

    call base_allocate_system(nr_of_proc, volume, system_name, buffer_parameter, threshold_parameter, execution_steps, save_limit)

    unit_cell_size(1, 1) = 2.8892
    unit_cell_size(1, 2) = 0.0
    unit_cell_size(1, 3) = 0.0
    unit_cell_size(2, 1) = 0.0
    unit_cell_size(2, 2) = 26.0028
    unit_cell_size(2, 3) = 0.0
    unit_cell_size(3, 1) = 0.0
    unit_cell_size(3, 2) = 0.0
    unit_cell_size(3, 3) = 28.892000000000003
    site_positions(1,:) = (/0.5, 0.0, 0.0/)
    site_positions(2,:) = (/0.5, 0.0, 0.09090909090909091/)
    site_positions(3,:) = (/0.5, 0.0, 0.18181818181818182/)
    site_positions(4,:) = (/0.5, 0.0, 0.2727272727272727/)
    site_positions(5,:) = (/0.5, 0.0, 0.36363636363636365/)
    site_positions(6,:) = (/0.5, 0.0, 0.45454545454545453/)
    site_positions(7,:) = (/0.5, 0.0, 0.5454545454545454/)
    site_positions(8,:) = (/0.5, 0.0, 0.6363636363636364/)
    site_positions(9,:) = (/0.5, 0.0, 0.7272727272727273/)
    site_positions(10,:) = (/0.5, 0.0, 0.8181818181818182/)
    site_positions(11,:) = (/0.5, 0.0, 0.9090909090909091/)
    site_positions(12,:) = (/0.5, 0.1, 0.0/)
    site_positions(13,:) = (/0.5, 0.1, 0.09090909090909091/)
    site_positions(14,:) = (/0.5, 0.1, 0.18181818181818182/)
    site_positions(15,:) = (/0.5, 0.1, 0.2727272727272727/)
    site_positions(16,:) = (/0.5, 0.1, 0.36363636363636365/)
    site_positions(17,:) = (/0.5, 0.1, 0.45454545454545453/)
    site_positions(18,:) = (/0.5, 0.1, 0.5454545454545454/)
    site_positions(19,:) = (/0.5, 0.1, 0.6363636363636364/)
    site_positions(20,:) = (/0.5, 0.1, 0.7272727272727273/)
    site_positions(21,:) = (/0.5, 0.1, 0.8181818181818182/)
    site_positions(22,:) = (/0.5, 0.1, 0.9090909090909091/)
    site_positions(23,:) = (/0.5, 0.2, 0.0/)
    site_positions(24,:) = (/0.5, 0.2, 0.09090909090909091/)
    site_positions(25,:) = (/0.5, 0.2, 0.18181818181818182/)
    site_positions(26,:) = (/0.5, 0.2, 0.2727272727272727/)
    site_positions(27,:) = (/0.5, 0.2, 0.36363636363636365/)
    site_positions(28,:) = (/0.5, 0.2, 0.45454545454545453/)
    site_positions(29,:) = (/0.5, 0.2, 0.5454545454545454/)
    site_positions(30,:) = (/0.5, 0.2, 0.6363636363636364/)
    site_positions(31,:) = (/0.5, 0.2, 0.7272727272727273/)
    site_positions(32,:) = (/0.5, 0.2, 0.8181818181818182/)
    site_positions(33,:) = (/0.5, 0.2, 0.9090909090909091/)
    site_positions(34,:) = (/0.5, 0.3, 0.0/)
    site_positions(35,:) = (/0.5, 0.3, 0.09090909090909091/)
    site_positions(36,:) = (/0.5, 0.3, 0.18181818181818182/)
    site_positions(37,:) = (/0.5, 0.3, 0.2727272727272727/)
    site_positions(38,:) = (/0.5, 0.3, 0.36363636363636365/)
    site_positions(39,:) = (/0.5, 0.3, 0.45454545454545453/)
    site_positions(40,:) = (/0.5, 0.3, 0.5454545454545454/)
    site_positions(41,:) = (/0.5, 0.3, 0.6363636363636364/)
    site_positions(42,:) = (/0.5, 0.3, 0.7272727272727273/)
    site_positions(43,:) = (/0.5, 0.3, 0.8181818181818182/)
    site_positions(44,:) = (/0.5, 0.3, 0.9090909090909091/)
    site_positions(45,:) = (/0.5, 0.4, 0.0/)
    site_positions(46,:) = (/0.5, 0.4, 0.09090909090909091/)
    site_positions(47,:) = (/0.5, 0.4, 0.18181818181818182/)
    site_positions(48,:) = (/0.5, 0.4, 0.2727272727272727/)
    site_positions(49,:) = (/0.5, 0.4, 0.36363636363636365/)
    site_positions(50,:) = (/0.5, 0.4, 0.45454545454545453/)
    site_positions(51,:) = (/0.5, 0.4, 0.5454545454545454/)
    site_positions(52,:) = (/0.5, 0.4, 0.6363636363636364/)
    site_positions(53,:) = (/0.5, 0.4, 0.7272727272727273/)
    site_positions(54,:) = (/0.5, 0.4, 0.8181818181818182/)
    site_positions(55,:) = (/0.5, 0.4, 0.9090909090909091/)
    site_positions(56,:) = (/0.5, 0.5, 0.0/)
    site_positions(57,:) = (/0.5, 0.5, 0.09090909090909091/)
    site_positions(58,:) = (/0.5, 0.5, 0.18181818181818182/)
    site_positions(59,:) = (/0.5, 0.5, 0.2727272727272727/)
    site_positions(60,:) = (/0.5, 0.5, 0.36363636363636365/)
    site_positions(61,:) = (/0.5, 0.5, 0.45454545454545453/)
    site_positions(62,:) = (/0.5, 0.5, 0.5454545454545454/)
    site_positions(63,:) = (/0.5, 0.5, 0.6363636363636364/)
    site_positions(64,:) = (/0.5, 0.5, 0.7272727272727273/)
    site_positions(65,:) = (/0.5, 0.5, 0.8181818181818182/)
    site_positions(66,:) = (/0.5, 0.5, 0.9090909090909091/)
    site_positions(67,:) = (/0.5, 0.6, 0.0/)
    site_positions(68,:) = (/0.5, 0.6, 0.09090909090909091/)
    site_positions(69,:) = (/0.5, 0.6, 0.18181818181818182/)
    site_positions(70,:) = (/0.5, 0.6, 0.2727272727272727/)
    site_positions(71,:) = (/0.5, 0.6, 0.36363636363636365/)
    site_positions(72,:) = (/0.5, 0.6, 0.45454545454545453/)
    site_positions(73,:) = (/0.5, 0.6, 0.5454545454545454/)
    site_positions(74,:) = (/0.5, 0.6, 0.6363636363636364/)
    site_positions(75,:) = (/0.5, 0.6, 0.7272727272727273/)
    site_positions(76,:) = (/0.5, 0.6, 0.8181818181818182/)
    site_positions(77,:) = (/0.5, 0.6, 0.9090909090909091/)
    site_positions(78,:) = (/0.5, 0.7, 0.0/)
    site_positions(79,:) = (/0.5, 0.7, 0.09090909090909091/)
    site_positions(80,:) = (/0.5, 0.7, 0.18181818181818182/)
    site_positions(81,:) = (/0.5, 0.7, 0.2727272727272727/)
    site_positions(82,:) = (/0.5, 0.7, 0.36363636363636365/)
    site_positions(83,:) = (/0.5, 0.7, 0.45454545454545453/)
    site_positions(84,:) = (/0.5, 0.7, 0.5454545454545454/)
    site_positions(85,:) = (/0.5, 0.7, 0.6363636363636364/)
    site_positions(86,:) = (/0.5, 0.7, 0.7272727272727273/)
    site_positions(87,:) = (/0.5, 0.7, 0.8181818181818182/)
    site_positions(88,:) = (/0.5, 0.7, 0.9090909090909091/)
    site_positions(89,:) = (/0.5, 0.8, 0.0/)
    site_positions(90,:) = (/0.5, 0.8, 0.09090909090909091/)
    site_positions(91,:) = (/0.5, 0.8, 0.18181818181818182/)
    site_positions(92,:) = (/0.5, 0.8, 0.2727272727272727/)
    site_positions(93,:) = (/0.5, 0.8, 0.36363636363636365/)
    site_positions(94,:) = (/0.5, 0.8, 0.45454545454545453/)
    site_positions(95,:) = (/0.5, 0.8, 0.5454545454545454/)
    site_positions(96,:) = (/0.5, 0.8, 0.6363636363636364/)
    site_positions(97,:) = (/0.5, 0.8, 0.7272727272727273/)
    site_positions(98,:) = (/0.5, 0.8, 0.8181818181818182/)
    site_positions(99,:) = (/0.5, 0.8, 0.9090909090909091/)
    site_positions(100,:) = (/0.5, 0.9, 0.0/)
    site_positions(101,:) = (/0.5, 0.9, 0.09090909090909091/)
    site_positions(102,:) = (/0.5, 0.9, 0.18181818181818182/)
    site_positions(103,:) = (/0.5, 0.9, 0.2727272727272727/)
    site_positions(104,:) = (/0.5, 0.9, 0.36363636363636365/)
    site_positions(105,:) = (/0.5, 0.9, 0.45454545454545453/)
    site_positions(106,:) = (/0.5, 0.9, 0.5454545454545454/)
    site_positions(107,:) = (/0.5, 0.9, 0.6363636363636364/)
    site_positions(108,:) = (/0.5, 0.9, 0.7272727272727273/)
    site_positions(109,:) = (/0.5, 0.9, 0.8181818181818182/)
    site_positions(110,:) = (/0.5, 0.9, 0.9090909090909091/)
end subroutine allocate_system

subroutine deallocate_system()

!****f* lattice/deallocate_system
! FUNCTION
!    Deallocates system including mapping cache.
!
! ARGUMENTS
!
!    ``none``
!******
    deallocate(lattice2nr)
    deallocate(nr2lattice)
    call base_deallocate_system()

end subroutine deallocate_system

subroutine add_proc(proc, site)

    integer(kind=iint), intent(in) :: proc
    integer(kind=iint), dimension(4), intent(in) :: site

    integer(kind=iint) :: nr

    nr = lattice2nr(site(1), site(2), site(3), site(4))
    call base_add_proc(proc, nr)

end subroutine add_proc

subroutine del_proc(proc, site)

    integer(kind=iint), intent(in) :: proc
    integer(kind=iint), dimension(4), intent(in) :: site

    integer(kind=iint) :: nr

    nr = lattice2nr(site(1), site(2), site(3), site(4))
    call base_del_proc(proc, nr)

end subroutine del_proc

pure function can_do(proc, site)

    logical :: can_do
    integer(kind=iint), intent(in) :: proc
    integer(kind=iint), dimension(4), intent(in) :: site

    integer(kind=iint) :: nr

    nr = lattice2nr(site(1), site(2), site(3), site(4))
    can_do = base_can_do(proc, nr)

end function can_do

subroutine replace_species(site,  old_species, new_species)

    integer(kind=iint), dimension(4), intent(in) ::site
    integer(kind=iint), intent(in) :: old_species, new_species

    integer(kind=iint) :: nr

    nr = lattice2nr(site(1), site(2), site(3), site(4))
    call base_replace_species(nr, old_species, new_species)

end subroutine replace_species

pure function get_species(site)

    integer(kind=iint) :: get_species
    integer(kind=iint), dimension(4), intent(in) :: site
    integer(kind=iint) :: nr

    nr = lattice2nr(site(1), site(2), site(3), site(4))
    get_species = base_get_species(nr)

end function get_species

subroutine reset_site(site, old_species)

    integer(kind=iint), dimension(4), intent(in) :: site
    integer(kind=iint), intent(in) :: old_species

    integer(kind=iint) :: nr

    nr = lattice2nr(site(1), site(2), site(3), site(4))
    call base_reset_site(nr, old_species)

end subroutine reset_site

end module lattice
